model:
  input_dim: 480 # ESM-2 embedding dimension
  hidden_dims: [256, 128] # Hidden layer dimensions
  output_dim: 1 # Predict single expression value per gene
  n_heads: [4, 4, 1] # Number of attention heads for input, hidden, and output layers
  dropout: 0.1

training:
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  num_epochs: 100
